/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emergencyDoctor;

/**
 *
 * @author Ashadullah Shawon
 */
import java.text.DecimalFormat;
import javax.swing.*;
import java.io.*;
import com.sun.media.jfxmedia.logging.Logger;
import java.util.logging.Level;
public class EmergencyDoctor extends javax.swing.JFrame {

    /**
     * Creates new form EmergencyDoctor
     */
     static int st=2;
    public EmergencyDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        b = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        iw = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        g = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ht = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        m = new javax.swing.JCheckBox();
        f = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        iw1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cal = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hei = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        wei = new javax.swing.JTextField();
        male = new javax.swing.JCheckBox();
        fe = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        cl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        et = new javax.swing.JPanel();
        cb = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtf1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbt1 = new javax.swing.JButton();
        jbt2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        bmi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jButton15 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        wwp = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        calorie = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fib = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        wp = new javax.swing.JLabel();
        bp = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        sys = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        dias = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        pre = new javax.swing.JTextArea();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cf = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dis = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        trt = new javax.swing.JTextArea();
        jButton11 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        q = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(831, 632));
        setResizable(false);

        parent.setBackground(new java.awt.Color(236, 236, 236));
        parent.setLayout(new java.awt.CardLayout());

        b.setPreferredSize(new java.awt.Dimension(831, 580));
        b.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel23.setText("EmerGency Doctor");
        b.add(jLabel23);
        jLabel23.setBounds(370, 280, 460, 80);

        jButton14.setBackground(new java.awt.Color(0, 102, 51));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Start By Your Blood Pressure Checking");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        b.add(jButton14);
        jButton14.setBounds(430, 380, 330, 70);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emergencyDoctor/edb2.jpg"))); // NOI18N
        b.add(jLabel25);
        jLabel25.setBounds(0, 0, 830, 640);

        parent.add(b, "card10");

        jPanel6.setBackground(new java.awt.Color(236, 236, 236));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        parent.add(jPanel6, "card6");

        iw.setBackground(new java.awt.Color(236, 236, 236));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Enter  Age");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Enter Height");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Feet");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Inch");

        m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        m.setText("Male");

        f.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        f.setText("Female");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        iw1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout iwLayout = new javax.swing.GroupLayout(iw);
        iw.setLayout(iwLayout);
        iwLayout.setHorizontalGroup(
            iwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iwLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(iwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iwLayout.createSequentialGroup()
                        .addGroup(iwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(iwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(iwLayout.createSequentialGroup()
                                .addComponent(ht, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(iwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(iwLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(iwLayout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(85, 85, 85)
                                        .addComponent(jButton4))))))
                    .addGroup(iwLayout.createSequentialGroup()
                        .addComponent(m)
                        .addGap(33, 33, 33)
                        .addComponent(f)))
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iwLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iw1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        iwLayout.setVerticalGroup(
            iwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iwLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(iwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(iwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(ht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(iwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(hi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(31, 31, 31)
                .addGroup(iwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m)
                    .addComponent(f))
                .addGap(82, 82, 82)
                .addGroup(iwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(iw1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        parent.add(iw, "card7");

        cal.setBackground(new java.awt.Color(236, 236, 236));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Enter Age");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Height");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Weight");

        male.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        male.setText("Male");

        fe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fe.setText("Female");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Inch");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Kg");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout calLayout = new javax.swing.GroupLayout(cal);
        cal.setLayout(calLayout);
        calLayout.setHorizontalGroup(
            calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calLayout.createSequentialGroup()
                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                            .addComponent(jLabel12)
                            .addComponent(male))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fe)
                            .addGroup(calLayout.createSequentialGroup()
                                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hei)
                                    .addComponent(age)
                                    .addComponent(wei, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addGroup(calLayout.createSequentialGroup()
                                        .addGap(168, 168, 168)
                                        .addComponent(jButton3))))))
                    .addGroup(calLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(cl, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        calLayout.setVerticalGroup(
            calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(37, 37, 37)
                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(wei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(28, 28, 28)
                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(fe))
                .addGap(39, 39, 39)
                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(cl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        parent.add(cal, "card5");

        et.setBackground(new java.awt.Color(236, 236, 236));
        et.setLayout(null);

        cb.setBackground(new java.awt.Color(0, 102, 51));
        cb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb.setForeground(new java.awt.Color(255, 255, 255));
        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Headache", "Cold", "Belly Pain", "Gas", "Food Poisoning", "Fever", "Irritations", "Diabetis", "Bone Pain", "Skin Disease", "Tonsil", "Cough", "High Pressure", "Calcium", "Vomit", "Worms" }));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        et.add(cb);
        cb.setBounds(39, 92, 171, 23);

        jtf1.setColumns(20);
        jtf1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jtf1.setRows(5);
        jScrollPane2.setViewportView(jtf1);

        et.add(jScrollPane2);
        jScrollPane2.setBounds(252, 66, 492, 345);

        jLabel4.setBackground(new java.awt.Color(0, 102, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select Your Disease");
        et.add(jLabel4);
        jLabel4.setBounds(39, 21, 187, 26);

        jLabel5.setBackground(new java.awt.Color(0, 102, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("             Prescription");
        et.add(jLabel5);
        jLabel5.setBounds(390, 21, 177, 27);

        jbt1.setBackground(new java.awt.Color(0, 102, 51));
        jbt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbt1.setForeground(new java.awt.Color(255, 255, 255));
        jbt1.setText("Save");
        jbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt1ActionPerformed(evt);
            }
        });
        et.add(jbt1);
        jbt1.setBounds(355, 429, 82, 34);

        jbt2.setBackground(new java.awt.Color(0, 102, 51));
        jbt2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbt2.setForeground(new java.awt.Color(255, 255, 255));
        jbt2.setText("Reset");
        jbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt2ActionPerformed(evt);
            }
        });
        et.add(jbt2);
        jbt2.setBounds(596, 429, 86, 34);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emergencyDoctor/m1.jpg"))); // NOI18N
        et.add(jLabel26);
        jLabel26.setBounds(0, 0, 830, 600);

        parent.add(et, "card3");

        bmi.setBackground(new java.awt.Color(236, 236, 236));
        bmi.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 252, 252));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                         Check Your BMI");
        bmi.add(jLabel1);
        jLabel1.setBounds(231, 11, 309, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Your  Weight  (KG)");
        bmi.add(jLabel2);
        jLabel2.setBounds(50, 61, 164, 45);
        bmi.add(tf1);
        tf1.setBounds(50, 115, 164, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Your Height  (Inch)");
        bmi.add(jLabel3);
        jLabel3.setBounds(50, 200, 155, 36);
        bmi.add(tf2);
        tf2.setBounds(50, 240, 164, 29);

        btn.setBackground(new java.awt.Color(0, 102, 51));
        btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setText("Check BMI");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        bmi.add(btn);
        btn.setBounds(60, 310, 130, 60);

        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        bmi.add(jScrollPane1);
        jScrollPane1.setBounds(305, 61, 502, 278);

        jButton15.setBackground(new java.awt.Color(0, 102, 51));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Reset");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        bmi.add(jButton15);
        jButton15.setBounds(60, 410, 130, 50);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emergencyDoctor/stock-photo-body-mass-index-bmi-259650215.jpg"))); // NOI18N
        bmi.add(jLabel28);
        jLabel28.setBounds(0, 0, 830, 600);

        parent.add(bmi, "card2");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Enter Food Calorie");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Enter Food Fat");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Enter Food Fibre");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Calculate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        wp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout wwpLayout = new javax.swing.GroupLayout(wwp);
        wwp.setLayout(wwpLayout);
        wwpLayout.setHorizontalGroup(
            wwpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wwpLayout.createSequentialGroup()
                .addGroup(wwpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wwpLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(wwpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(33, 33, 33)
                        .addGroup(wwpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fat)
                            .addComponent(calorie)
                            .addComponent(fib, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                    .addGroup(wwpLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jButton5)
                        .addGap(65, 65, 65)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wwpLayout.createSequentialGroup()
                .addGap(0, 250, Short.MAX_VALUE)
                .addComponent(wp, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        wwpLayout.setVerticalGroup(
            wwpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wwpLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(wwpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(calorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(wwpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(fat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(wwpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(fib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(wwpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(96, 96, 96)
                .addComponent(wp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        parent.add(wwp, "card6");

        bp.setLayout(null);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Enter Systolic Pressure");
        bp.add(jLabel18);
        jLabel18.setBounds(72, 11, 158, 60);
        bp.add(sys);
        sys.setBounds(238, 26, 136, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Enter Diastolic Pressure");
        bp.add(jLabel19);
        jLabel19.setBounds(72, 94, 162, 30);
        bp.add(dias);
        dias.setBounds(238, 94, 136, 30);

        jButton7.setBackground(new java.awt.Color(0, 102, 51));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Calculate");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        bp.add(jButton7);
        jButton7.setBounds(257, 182, 95, 30);

        jButton8.setBackground(new java.awt.Color(0, 102, 51));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        bp.add(jButton8);
        jButton8.setBounds(394, 182, 90, 30);

        pre.setColumns(20);
        pre.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pre.setRows(5);
        jScrollPane6.setViewportView(pre);

        bp.add(jScrollPane6);
        jScrollPane6.setBounds(156, 245, 523, 221);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emergencyDoctor/b2.jpg"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        bp.add(jButton12);
        jButton12.setBounds(744, 131, 64, 63);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emergencyDoctor/b1.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        bp.add(jButton13);
        jButton13.setBounds(635, 131, 64, 64);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Find More Treatment");
        bp.add(jLabel22);
        jLabel22.setBounds(644, 81, 156, 17);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emergencyDoctor/blood-pressure-monitor-by-joey-parsons.jpg"))); // NOI18N
        bp.add(jLabel24);
        jLabel24.setBounds(0, 0, 830, 600);

        parent.add(bp, "card8");

        cf.setLayout(null);

        jButton9.setBackground(new java.awt.Color(0, 102, 51));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Yes");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        cf.add(jButton9);
        jButton9.setBounds(250, 140, 57, 25);

        jButton10.setBackground(new java.awt.Color(0, 102, 51));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("No");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        cf.add(jButton10);
        jButton10.setBounds(360, 140, 53, 25);

        jLabel20.setBackground(new java.awt.Color(0, 102, 51));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Disease");
        cf.add(jLabel20);
        jLabel20.setBounds(360, 170, 51, 17);

        dis.setEditable(false);
        dis.setColumns(20);
        dis.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        dis.setRows(5);
        dis.setText("                 \n\n                  ");
        jScrollPane3.setViewportView(dis);

        cf.add(jScrollPane3);
        jScrollPane3.setBounds(120, 190, 570, 106);

        jLabel21.setBackground(new java.awt.Color(0, 102, 51));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Treatment");
        cf.add(jLabel21);
        jLabel21.setBounds(360, 300, 73, 17);

        trt.setEditable(false);
        trt.setColumns(20);
        trt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        trt.setRows(5);
        jScrollPane4.setViewportView(trt);

        cf.add(jScrollPane4);
        jScrollPane4.setBounds(63, 322, 720, 220);

        jButton11.setBackground(new java.awt.Color(0, 102, 51));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Reset");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        cf.add(jButton11);
        jButton11.setBounds(460, 140, 71, 25);

        q.setEditable(false);
        q.setColumns(20);
        q.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        q.setRows(5);
        q.setText(" \n                   Do You Have A Fever?");
        jScrollPane5.setViewportView(q);

        cf.add(jScrollPane5);
        jScrollPane5.setBounds(155, 11, 486, 123);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emergencyDoctor/m1.jpg"))); // NOI18N
        cf.add(jLabel27);
        jLabel27.setBounds(0, 0, 830, 600);

        parent.add(cf, "card9");

        getContentPane().add(parent, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText(" Health Checking");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem9.setText("Start Page");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);
        jMenu1.add(jSeparator5);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setText("Check BMI");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem3.setText("Ideal Weight");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator2);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setText("Calori ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator3);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem6.setText("Weight Watchers Point");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("   Emergency  Treatment");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setText("Emergency Medicine");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        jMenu2.add(jSeparator4);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem7.setText("Check Blood Pressure");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setText("  Symptoms And Treatment");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem8.setText("Cold And Flu");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setText("   About");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem4.setText("Developer");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(bmi);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        String n=System.lineSeparator();
        float h,w,bmi,i;
        w=Float.parseFloat(tf1.getText());
        i=Float.parseFloat(tf2.getText());
        h=(float) ((0.3048/12.00)*i);
        bmi=w/(h*h);
        DecimalFormat df=new DecimalFormat("#.##");
        ta.setText("Your BMI Is="+df.format(bmi)+"\n");
        
        
        if(bmi>=0 && bmi<=18.50)
        {
            ta.append("Oops!! You are Underweight.Eat Healthy Food Regularly.");
        }
        else if(bmi>=18.51 && bmi<=24.9)
        {
            ta.append("Congrats!! You are Normal.Keep It Up");
        }
        else if(bmi>=24.91 && bmi<=29.9)
        {
            ta.append("OH!! You Are Overweight.You Should start Exercise");
        }
        else if(bmi>=29.91)
        {
            ta.append("OMG!! You are Obese.Aloof from Over Eating As well as Laziness\n And Start Hard Exercise");
        }
        
        
       
       
        
    }//GEN-LAST:event_btnActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
        String n=System.lineSeparator();
        if(cb.getSelectedItem()=="Headache")
        {
            jtf1.setText("Rx \n Medicine Name: Napa 500 Mg\n During: 2 Times \n Morning- After Breakfast \n Night-After Dinner.");
        }
        else if(cb.getSelectedItem()=="Cold")
        {
            jtf1.setText("Rx \n Medicine Name: Histacin Or Sinamin , Deslon \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
        else if(cb.getSelectedItem()=="Bone Pain")
        {
             jtf1.setText("Rx \n Medicine Name: Duloxim \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="Cough")
        {
             jtf1.setText("Rx \n Medicine Name: Tuska ,Tomifen (Heavy Cough), Phenargan, Mucolyt(Cough)\n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="Diabetis")
        {
             jtf1.setText("Rx \n Medicine Name: Oclazit \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="Irritations")
        {
             jtf1.setText("Rx \n Medicine Name: Xyril (25 mg), Rupex(10 mg) \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="Fever")
        {
             jtf1.setText("Rx \n Medicine Name: Paraclot+ Napa \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="Vomit")
        {
             jtf1.setText("Rx \n Medicine Name: Otosil \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="Gas")
        {
             jtf1.setText("Rx \n Medicine Name: Pantonix, Losectil \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="Belly Pain")
        {
             jtf1.setText("Rx \n Medicine Name: Nospa \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="Food Poisoning")
        {
             jtf1.setText("Rx \n Medicine Name: Imotil+Salaine \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
        else if(cb.getSelectedItem()=="Calcium")
        {
             jtf1.setText("Rx \n Medicine Name: Rocal-D-Vita \n During: 2 Times \n Morning- After Breakfast \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="High Pressure")
        {
             jtf1.setText("Rx \n Medicine Name: Camlodin Plus \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="Tonsil")
        {
             jtf1.setText("Rx \n Medicine Name: Tisil \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="Skin Disease")
        {
             jtf1.setText("Rx \n Medicine Name: Nyclobate NN \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
          else if(cb.getSelectedItem()=="Worms")
        {
             jtf1.setText("Rx \n Medicine Name: Alben \n During: 3 Times \n Morning- After Breakfast \n Noon-After Lunch \n Night-After Dinner.");
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_cbActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(et);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt1ActionPerformed
        // TODO add your handling code here:
         JFileChooser jfc=new JFileChooser();
        if(jfc.showSaveDialog(jbt1)==JFileChooser.APPROVE_OPTION)
        {
            try {
                PrintWriter fout=new PrintWriter(jfc.getSelectedFile());
                fout.print(jtf1.getText());
                fout.close();
            } catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(EmergencyDoctor.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
    }//GEN-LAST:event_jbt1ActionPerformed

    private void jbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt2ActionPerformed
        // TODO add your handling code here:
        jtf1.setText("");
    }//GEN-LAST:event_jbt2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double n,weight;
        n=Double.parseDouble(hi.getText().toString());
        if(m.isSelected()==true)
        {
           weight=52.0+n*1.9;
           iw1.setText("Your Ideal Weight Is="+weight+" Kg");
        }
        if(f.isSelected()==true)
        {
            weight=49.0+n*1.7;
            iw1.setText("Your Ideal Weight Is="+weight+" Kg");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(iw);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double a,h,w,i,c;
        int mc=0,wc=0;
        a=Double.parseDouble(age.getText());
        h=Double.parseDouble(hei.getText());
        w=Double.parseDouble(wei.getText());
        if(male.isSelected()==true)
        {
            mc=1;
            wc=0;
           
            i=((h*30.48)/12.00);
	    c=(10*w+(6.25*i)-(5*a)+5);
	    DecimalFormat df=new DecimalFormat("#.##");
            cl.setText("You Need ="+df.format(c)+" Calories     Per Day");
            
        }
       else if(fe.isSelected()==true)
        {
     
            wc=1;
            mc=0;
          
            i=((h*30.48)/12.00);
	    c=(10*w+(6.25*i)-(5*a)-161);
	    DecimalFormat df=new DecimalFormat("#.##");
	    cl.setText("You Need ="+df.format(c)+" Calories     Per Day");
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(cal);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        age.setText("");
        hei.setText("");
        wei.setText("");
        cl.setText("");
        male.setSelected(false);
        fe.setSelected(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         g.setText("");
        hi.setText("");
        ht.setText("");
        m.setSelected(false);
        f.setSelected(false);
        iw1.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        double ca,fa,fi,m=4,p;
        int tp;
        ca=Double.parseDouble(calorie.getText());
        fa=Double.parseDouble(fat.getText());
        fi=Double.parseDouble(fib.getText());
        if(fi<4)
        {
            m=fi;
        }
        p=(ca/50.0)+(fa/12.0)-(m/5);
        tp=(int) p;
        wp.setText("Food Weight Watchers Point is="+tp);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(wwp);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        calorie.setText("");
        fat.setText("");
        fib.setText("");
        wp.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(bp);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int s,d;
        String n=System.lineSeparator();
        s=Integer.parseInt(sys.getText());
        d=Integer.parseInt(dias.getText());
        if((s>=70 && s<=90) && (d>=40 && d<=70))
        {
            pre.setText("You  Low Blood Pressure\n\n"
                    + "Eat More Healthy Food That Have More Fat\n "
                    + "Example: Beaf, Mutton, Egg, Porn Etc");
         
        }
        else if((s>=90 && s<=120) && (d>=60 && d<=80))
        {
            pre.setText("You Have  Normal Blood Pressure\n\nEat Healthy Food Regularly And Avoid Food Those have High Fat");
        }
        else if((s>=120 && s<=140) && (d>=80 && d<=90))
        {
             pre.setText("You Have  Pre High Blood Pressure\n\n"
                     + "Stop Eating Food Those Have High Fat\n"
                     + "Beaf, Mutton, Egg, Porn, Oil Are Harmful For Your Health\n");
                   
        }
        else if((s>=190 && s<=140) && (d>=90 && d<=100))
        {
             pre.setText("You Have  High Blood Pressure!!!\n\n"
                     + "Totally Stop Eating Food Having High Fat And Oil\n\n"
                     + "Omit Beaf, Mutton, Egg, Porn, Oil From Your Food List\n"
                     + "Only Eat Food Those Have Less Oil Like Vegetables\n"
                     + "Chicken, Fish etc\n"
                     + "Start Regular Morning Exercise. Talk to your doctor\n "
                     + "about taking more ");
        }
        else
        {
            pre.setText("Wrong Input!!!");
        }
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        sys.setText("");
        dias.setText("");
        pre.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String[] str=new String[20];
        String n=System.lineSeparator();
        str[1]="Do You Have A Fever?";
        str[2]=" Do you have a sore throat and headache--without nasal drainage?";
        str[3]=" Did your symptoms start suddenly, and do you have a combination of symptoms including muscle aches, chills, a sore throat, runny nose or cough?";
        str[4]="Do you have a persistent cough that brings up yellowish or greenish mucus, wheezing and shortness of breath.";
        str[5]="D0 You Have A Headache Or Muscle Aches,nausea Or Vomiting And Watery Diarrhea? ";
        str[6]="Do You Have runny Or itchy Nose,sneezing And Itchy Eyes?";
        str[7]="Do You Have sneezing,a sore throat,headache,congestion, and a Runny nose? ";
        str[8]=" Do you have swelling or pain around your eyes, cheeks, nose or forehead, a headache, a dry cough, and/or discharge from the nose?";
      
       if(st==2)
       {
            q.setText(" Do you have a sore throat and\n"
                    + " headache--without nasal drainage?");
            st++;
            
       }
      
       else if(st==3)
       {
          dis.setText("You may have STREP THROAT, a bacterial infection.");
           trt.setText("See your doctor if the sore throat or fever lasts longer than 48 hours. \n"
                   + "He or she can do a test to find out if you have strep throat. If you do,\n "
                   + "your doctor may give you an antibiotic to treat it. You should also get\n"
                   + " plenty of rest, and drink lots of water. Gargling with warm salt water\n "
                   + "may help relieve a sore throat.");
           
       }
       else if(st==4)
       {
           dis.setText("You may have the FLU.");
           trt.setText("Get plenty of rest, and drink lots of fluids. Over-the-counter medicines\n "
                   + "may relieve some of your symptoms. Your doctor may suggest a prescription\n"
                   + " medicine that may shorten the course of the flu. Prevent the flu by getting\n"
                   + " a flu shot each fall.");
       }
       else if(st==5)
       {
           dis.setText("You may be developing ACUTE BRONCHITIS, an infection of the airways.");
           trt.setText("Get plenty of rest, and drink lots of fluids. If you smoke, cut down on the number\n"
                   + " of cigarettes you smoke, or stop smoking. Use an over-the-counter medicine for pain\n"
                   + " and fever, and an expectorant to ease the coughing. A humidifier may also relieve\n"
                   + " some symptoms. If symptoms persist or worsen, contact your doctor.");
       }
       else if(st==6)
       {
           dis.setText("You may have GASTROENTERITIS (also called the stomach flu).");
           trt.setText("Get plenty of rest. Children who have gastroenteritis should\n "
                   + "be given an oral rehydration solution to avoid dehydration. Ease\n "
                   + "back into eating with bland foods and clear liquids.\n");
       }
       else if(st==7)
       {
           
           dis.setText("You May Have Allergies");
           trt.setText("Try An Over The Counter antihistamine medicine.\nIf symptoms persist or worsen,contact your doctor");
       }
       else if(st==8)
       {
  
           dis.setText("You Probably Have a Cold");
           trt.setText("Try An Over the counter cold Medicine to treat the \n"
                   + "specifiq symptoms you are having.\nGet Plenty OF Rest\n"
                   + " And Drink Lots OF Fluid.");
       }
       else if(st==9)
       {
           dis.setText("You May Be Developing Sinusits.");
           trt.setText("\nSee Your Doctor. Acetaminophen,ibuprofen or warm \n"
                   + "compresses may help reduce facial pain. A cool Mist\n "
                   + "Vaporizer May Help Your sinuses drain more easily .\n "
                   + "Drink Plenty OF Fluids.");
       }
       
       
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(cf);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String[] str=new String[20];
        String n=System.lineSeparator();
        int stn=0;
        stn++;
        str[1]="Do You Have A Fever?";
        str[2]=" Do you have a sore throat and headache--without nasal drainage?";
        str[3]=" Did your symptoms start suddenly, and do you have a combination of symptoms including muscle aches, chills, a sore throat, runny nose or cough?";
        str[4]="Do you have a persistent cough that brings up yellowish or greenish mucus, wheezing and shortness of breath.";
        str[5]="D0 You Have A Headache Or Muscle Aches,nausea Or Vomiting And Watery Diarrhea? ";
        str[6]="Do You Have runny Or itchy Nose,sneezing And Itchy Eyes?";
        str[7]="Do You Have sneezing,a sore throat,headache,congestion, and a Runny nose? ";
        str[8]=" Do you have swelling or pain around your eyes, cheeks, nose or forehead, a headache, a dry cough, and/or discharge from the nose?";
      
       if(st==2)
       {
           q.setText("Do You Have runny Or itchy Nose,\n"
                   + "Sneezing And Itchy Eyes?");
           st=st+5;
         
       }
       else if(st==3)
       {
           q.setText("Did your symptoms start suddenly, "
                   + "and do you have a combination\n"
                   + " of symptoms including muscle aches,\n "
                   + "chills, a sore throat,\n "
                   + "runny nose or cough?");
           st++;
       }
       else if(st==4)
       {
           q.setText("Do you have a persistent cough that\n"
                   + " brings up yellowish or greenish mucus,\n "
                   + "wheezing and shortness of breath.");
           st++;
       }
       else if(st==5)
       {
           q.setText("Do you have a headache or muscle aches,\n"
                   + " nausea or vomiting, and watery diarrhea?");
           st++;
       }
       else if(st==7)
       {
           q.setText(" Do you have sneezing, a sore throat, headache,\n "
                   + "congestion and a runny nose?");
           st++;
       }
       else if(st==8)
       {
           q.setText("Do you have swelling or pain around your eyes,\n"
                   + " cheeks, nose or forehead, a headache, a dry\n"
                   + " cough, and/or discharge from the nose? \n");
           st++;
       }
       
       else
       {
            trt.setText("For more information, please talk to your doctor.\nIf you think your problem is serious, call right away.\nTitle :\n" +
"Prof.Mahiuddin Ahmad\n" +
"Silver Member\n" +
"Address :\n" +
"MBBS (DMC), FCPS (Medicine), M.D (Chest Disease), Gold Medelist, Asst. Professor , National Institute Of Chest Disease, Mahakhali, Cham # Comfort Tower, 167/B, Green Road, Dhanmondi\n" +
"City :\n" +
"Dhaka\n" +
"Country :\n" +
"Bangladesh\n" +
"Phone :\n" +
"+880-2-8124990, 8124980\n" +
"");
       }
       
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        trt.setText("");
        dis.setText("");
        q.setText("Do You Have a Fever?");
        st=2;
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try
        {
            String url="http://www.prevention.com/health/how-lower-blood-pressure-naturally";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         try
        {
            String url="http://www.mayoclinic.org/diseases-conditions/high-blood-pressure/in-depth/high-blood-pressure/art-20046974";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(bp);
        parent.repaint();
        parent.revalidate();
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(b);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        tf2.setText("");
        ta.setText("");
        
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmergencyDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmergencyDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmergencyDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmergencyDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmergencyDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JPanel b;
    private javax.swing.JPanel bmi;
    private javax.swing.JPanel bp;
    private javax.swing.JButton btn;
    private javax.swing.JPanel cal;
    private javax.swing.JTextField calorie;
    private javax.swing.JComboBox cb;
    private javax.swing.JPanel cf;
    private javax.swing.JLabel cl;
    private javax.swing.JTextField dias;
    private javax.swing.JTextArea dis;
    private javax.swing.JPanel et;
    private javax.swing.JCheckBox f;
    private javax.swing.JTextField fat;
    private javax.swing.JCheckBox fe;
    private javax.swing.JTextField fib;
    private javax.swing.JTextField g;
    private javax.swing.JTextField hei;
    private javax.swing.JTextField hi;
    private javax.swing.JTextField ht;
    private javax.swing.JPanel iw;
    private javax.swing.JLabel iw1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JButton jbt1;
    private javax.swing.JButton jbt2;
    private javax.swing.JTextArea jtf1;
    private javax.swing.JCheckBox m;
    private javax.swing.JCheckBox male;
    private javax.swing.JPanel parent;
    private javax.swing.JTextArea pre;
    private javax.swing.JTextArea q;
    private javax.swing.JTextField sys;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextArea trt;
    private javax.swing.JTextField wei;
    private javax.swing.JLabel wp;
    private javax.swing.JPanel wwp;
    // End of variables declaration//GEN-END:variables
}
